Normalise build

diff --git a/.github/workflows/templates/update_dependencies/action.yml b/.github/workflows/templates/update_dependencies/action.yml
--- a/.github/workflows/templates/update_dependencies/action.yml
+++ b/.github/workflows/templates/update_dependencies/action.yml
@@ -75,53 +75,72 @@ runs:
         else
             echo "django_image_exists=false" >> $GITHUB_OUTPUT
         fi
-        if docker manifest inspect ${{ inputs.ecr_registry }}/${{ inputs.node_base_repository }}:latest >/dev/null; then
-            echo "node_image_latest_exists=true" >> $GITHUB_OUTPUT
-        else
-            echo "node_image_latest_exists=false" >> $GITHUB_OUTPUT
-        fi
-        if docker manifest inspect ${{ inputs.ecr_registry }}/${{ inputs.django_base_repository }}:latest >/dev/null; then
-            echo "django_image_latest_exists=true" >> $GITHUB_OUTPUT
-        else
-            echo "django_image_latest_exists=false" >> $GITHUB_OUTPUT
-        fi
 
     - name: "Build Node Base"
       id: build_node_base
       if: steps.check_for_node_change.outputs.changed == 'true' || steps.check_images.outputs.node_image_exists == 'false'
-      shell: bash
-      run: |    
-        echo "node_base_image=${{ inputs.ecr_registry }}/${{ inputs.node_base_repository }}:${{ inputs.docker_tag }}" >> $GITHUB_OUTPUT
-        aws ecr create-repository --repository-name ${{ inputs.node_base_repository }} || true
-        if [ "${{ steps.check_images.outputs.node_image_exists }}" = "true" ]; then
-          echo "${{ inputs.ecr_registry }}/${{ inputs.node_base_repository }}:${{ inputs.docker_tag }} not found" 
-          cachefrom="--cache-from ${{ inputs.ecr_registry }}/${{ inputs.node_base_repository }}:${{ inputs.docker_tag }}"
-        elif [ "${{ steps.check_images.outputs.node_image_latest_exists }}" = "true" ]; then
-          echo "${{ inputs.ecr_registry }}/${{ inputs.node_base_repository }}:latest not found" 
-          cachefrom="--cache-from ${{ inputs.ecr_registry }}/${{ inputs.node_base_repository }}:latest"
-        else
-          cachefrom=""
-        fi
-        echo $cachefrom
-        docker build $cachefrom -t ${{ inputs.ecr_registry }}/${{ inputs.node_base_repository }}:${{ inputs.docker_tag }} -f ./docker/production/node_base/Dockerfile .
-        docker push ${{ inputs.ecr_registry }}/${{ inputs.node_base_repository }} --all-tags
+      uses: "./.github/workflows/templates/docker_cached_build"
+      with:
+        ecr_registry: ${{ inputs.ecr_registry }}
+        repository: ${{ inputs.node_base_repository }}
+        docker_tag: ${{ inputs.docker_tag }}
+        dockerfile_location: "./docker/production/node_base/Dockerfile"
 
     - name: "Build Django Base"
       id: build_django_base
       if: steps.check_for_python_change.outputs.changed == 'true' || steps.check_images.outputs.django_image_exists == 'false'
-      shell: bash
-      run: |    
-        echo "django_base_image=${{ inputs.ecr_registry }}/${{ inputs.django_base_repository }}:${{ inputs.docker_tag }}" >> $GITHUB_OUTPUT
-        aws ecr create-repository --repository-name ${{ inputs.django_base_repository }} || true
-        if [ "${{ steps.check_images.outputs.django_image_exists }}" = "true" ]; then
-          echo "${{ inputs.ecr_registry }}/${{ inputs.django_base_repository }}:${{ inputs.docker_tag }} not found" 
-          cachefrom="--cache-from ${{ inputs.ecr_registry }}/${{ inputs.django_base_repository }}:${{ inputs.docker_tag }}"
-        elif [ "${{ steps.check_images.outputs.django_image_latest_exists }}" = "true" ]; then
-          echo "${{ inputs.ecr_registry }}/${{ inputs.django_base_repository }}:latest not found" 
-          cachefrom="--cache-from ${{ inputs.ecr_registry }}/${{ inputs.django_base_repository }}:latest"
-        else
-          cachefrom=""
-        fi
-        echo $cachefrom
-        docker build $cachefrom -t ${{ inputs.ecr_registry }}/${{ inputs.django_base_repository }}:${{ inputs.docker_tag }} -f ./docker/production/django_base/Dockerfile .
-        docker push ${{ inputs.ecr_registry }}/${{ inputs.django_base_repository }} --all-tags
+      uses: "./.github/workflows/templates/docker_cached_build"
+      with:
+        ecr_registry: ${{ inputs.ecr_registry }}
+        repository: ${{ inputs.django_base_repository }}
+        docker_tag: ${{ inputs.docker_tag }}
+        dockerfile_location: "./docker/production/django_base/Dockerfile"
+
+
+    # - name: "Build Node Base"
+    #   id: build_node_base
+    #   if: steps.check_for_node_change.outputs.changed == 'true' || steps.check_images.outputs.node_image_exists == 'false'
+    #   shell: bash
+    #   run: |    
+    #     node_base_image=${{ inputs.ecr_registry }}/${{ inputs.node_base_repository }}:${{ inputs.docker_tag }}
+    #     node_base_latest_image=${{ inputs.ecr_registry }}/${{ inputs.node_base_repository }}:latest
+    #     echo "node_base_image=${node_base_image}" >> $GITHUB_OUTPUT
+    #     aws ecr create-repository --repository-name ${{ inputs.node_base_repository }} || true
+    #     if [ "${{ steps.check_images.outputs.node_image_exists }}" = "true" ]; then
+    #       echo "${node_base_image} not found" 
+    #       cachefrom="--cache-from ${node_base_image}"
+    #       docker pull $node_base_image
+    #     elif [ "${{ steps.check_images.outputs.node_image_latest_exists }}" = "true" ]; then
+    #       echo "${node_base_latest_image} not found" 
+    #       cachefrom="--cache-from ${node_base_latest_image}"
+    #       docker pull $node_base_latest_image
+    #     else
+    #       cachefrom=""
+    #     fi
+    #     echo $cachefrom
+    #     docker build $cachefrom -t ${node_base_image} -f ./docker/production/node_base/Dockerfile .
+    #     docker push ${{ inputs.ecr_registry }}/${{ inputs.node_base_repository }} --all-tags
+
+    # - name: "Build Django Base"
+    #   id: build_django_base
+    #   if: steps.check_for_python_change.outputs.changed == 'true' || steps.check_images.outputs.django_image_exists == 'false'
+    #   shell: bash
+    #   run: |    
+    #     django_base_image=${{ inputs.ecr_registry }}/${{ inputs.django_base_repository }}:${{ inputs.docker_tag }}
+    #     django_base_latest_image=${{ inputs.ecr_registry }}/${{ inputs.django_base_repository }}:latest
+    #     echo "django_base_image=${django_base_image}" >> $GITHUB_OUTPUT
+    #     aws ecr create-repository --repository-name ${{ inputs.django_base_repository }} || true
+    #     if [ "${{ steps.check_images.outputs.django_image_exists }}" = "true" ]; then
+    #       echo "${django_base_image} not found" 
+    #       cachefrom="--cache-from ${django_base_image}"
+    #       docker pull $django_base_image
+    #     elif [ "${{ steps.check_images.outputs.django_image_latest_exists }}" = "true" ]; then
+    #       echo "${django_base_latest_image} not found" 
+    #       cachefrom="--cache-from ${django_base_latest_image}"
+    #       docker pull $django_base_latest_image
+    #     else
+    #       cachefrom=""
+    #     fi
+    #     echo $cachefrom
+    #     docker build $cachefrom -t ${django_base_image} -f ./docker/production/django_base/Dockerfile .
+    #     docker push ${{ inputs.ecr_registry }}/${{ inputs.django_base_repository }} --all-tags
